config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: 'restaurants#index'
  resources :restaurants, except: [:edit, :update, :destroy] do
    resources :reviews, except: [:edit, :update, :destroy, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  PERMITTED_CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: PERMITTED_CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true}
  validates :rating, inclusion: { in: RATINGS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def edit
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end


# new create

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>ALl Restaurants</h1>


    <!-- link_to TEXT, PATH -->
 <% @restaurants.each do |restaurant| %>


       <li><%= link_to restaurant.name, restaurant_path(restaurant) %>: <%= restaurant.category  %> | <%= restaurant.phone_number %> |<%= restaurant.address %> </li>
       <% end %>

app/views/restaurants/new.html.erb
<h1>Create New Restaurant Form</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name, label: 'Add Restaurant name' %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::PERMITTED_CATEGORIES %>
  <%= f.input :phone_number %>
  <%= f.button :submit %>

<% end %>

app/views/restaurants/show.html.erb
<h1> <%= @restaurant.name %> </h1>
<h2><%=  %></h2>

<ul>
 <% @restaurant.reviews.each do |review| %>
  <li><%= review.content %></li>
 <% end %>
</ul>

<div>
  <%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
</div>

<div>
  <%= link_to "Back to list", root_path %>

</div>

app/views/reviews/new.html.erb
<h1>Add New Review Form</h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content, label: 'Add New Review' %>
  <%= f.input :rating, collection: Review::RATINGS %>
  <%= f.button :submit %>

<% end %>